name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
# Cancel previous job on new commit for same branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-x86_64-unknown-linux-gnu
        components: rustfmt
    - name: Check f1-logic formatting
      run: cargo +nightly fmt --all -- --check
      working-directory: ./firmware/f1-logic
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.78
        components: llvm-tools
    - name : Run Tests for f1-logic
      run: cargo test --locked --target x86_64-unknown-linux-gnu
      working-directory: ./firmware/f1-logic
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.78
        targets: riscv32imc-unknown-none-elf
        components: llvm-tools
    - name: Build f1-logic
      run: cargo build --locked --release
      working-directory: ./firmware/f1-logic